language: node_js
node_js:
  - lts/*
cache: npm
os: linux
script:
  - npm run build

deploy:
  provider: pages
  strategy: git
  skip_cleanup: true
  local_dir: dist
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master
