#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1
jobs:
  deploy:
    docker:
      - image: circleci/node:latest
    working_directory: ~/repo
    steps:
      - add_ssh_keys:
          fingerprints:
            - "41:29:b8:1e:f9:f1:94:19:35:e8:22:19:36:92:36:d9"
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install node_modules
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: build app
          command: npm run build
      - run: mkdir ant-system
      - run: mv dist ant-system
      - run: rm -rf README.md package-lock.json vue.config.js jest.config.js package.json babel.config.js postcss.config.js .eslintrc.js .browserslistrc public src tests .git .circleci
      - run: ls -a
      - run: git init
      - run: git remote add origin https://github.com/xunmi1/xunmi1.github.io.git
      - run: git config --global user.email "xunmi1@outlook.com"
      - run: git config --global user.name "xunmi"

      - run: git add .

      - run: git commit -m "Update ant-system"
      - run: ls -a
      - run:
          name: Deploy Master to github.io
          command: git push -f origin master

workflows:
  version: 2.1
  deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: master
